---
- name: Restart Dock
  ansible.builtin.command: killall Dock
  changed_when: false

- name: Restart Finder
  ansible.builtin.command: killall Finder
  changed_when: false

- name: Restart Terminal
  ansible.builtin.command: killall Terminal
  changed_when: false
