---
git_user_name: "{{ lookup('env', 'GIT_USER_NAME') | default('Your Name', true) }}"
git_user_email: "{{ lookup('env', 'GIT_USER_EMAIL') | default('you@example.com', true) }}"
gpg_name: "{{ git_user_name }}"
gpg_email: "{{ git_user_email }}"
reset_gpg_key: false