---
- name: Set macOS preferences
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop:
    - { domain: "com.apple.dock", key: "autohide", type: "bool", value: true }
    - { domain: "com.apple.finder", key: "ShowPathbar", type: "bool", value: true }
    - { domain: "com.apple.finder", key: "ShowStatusBar", type: "bool", value: true }
    - { domain: "com.apple.screencapture", key: "type", type: "string", value: "jpg" }
    - { domain: "com.apple.desktopservices", key: "DSDontWriteNetworkStores", type: "bool", value: true }
    - { domain: "com.apple.dock", key: "orientation", type: "string", value: "left" }
    - { domain: "com.apple.dock", key: "tilesize", type: "float", value: 36 }
    - { domain: "com.apple.dock", key: "minimize-to-application", type: "bool", value: true }
  notify:
    - Restart Dock
    - Restart Finder