---
- name: Comprehensive SSH Setup with 1Password and AWS EC2 Support
  block:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'

    - name: Create AWS SSH proxy script
      template:
        src: aws-ssh-proxy.sh.j2
        dest: "{{ ansible_env.HOME }}/.ssh/aws-ssh-proxy.sh"
        mode: '0755'

    - name: Ensure SSH config file exists
      file:
        path: "{{ ansible_env.HOME }}/.ssh/config"
        state: touch
        mode: '0600'

    - name: Configure SSH
      template:
        src: ssh_config.j2
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        mode: '0600'

    - name: Configure SSH client for better security
      blockinfile:
        path: "{{ ansible_env.HOME }}/.ssh/config"
        block: |
          Host *
            KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
            HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
            Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
            MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
            IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

    - name: Install AWS CLI
      homebrew:
        name: awscli
        state: present

    - name: Install AWS Session Manager Plugin
      homebrew:
        name: session-manager-plugin
        state: present

  rescue:
    - name: Display error message
      debug:
        msg: "SSH setup failed. Please check the error messages and try again."

  always:
    - name: Ensure .ssh directory has correct permissions
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_env.USER }}"