- name: Configure tmux
  block:
    - name: Ensure tmux is installed
      homebrew:
        name: tmux
        state: present

    - name: Create tmux configuration directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.tmux"
        state: directory
        mode: '0755'

    - name: Copy tmux configuration file
      ansible.builtin.template:
        src: tmux.conf.j2
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        mode: '0644'

    - name: Clone TPM (Tmux Plugin Manager)
      ansible.builtin.git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
        version: master
        depth: 1

    - name: Install tmux plugins
      ansible.builtin.command: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"
      changed_when: false
