- name: Set up LazyVim
  block:
    - name: Ensure Neovim is installed
      homebrew:
        name: neovim
        state: present

    - name: Backup Neovim directories
      ansible.builtin.shell: |
        for dir in ~/.config/nvim ~/.local/state/nvim ~/.cache/nvim; do
          if [ -d "$dir" ] && [ ! -d "${dir}.bak" ]; then
            mv "$dir" "${dir}.bak"
          elif [ -d "$dir" ] && [ -d "${dir}.bak" ]; then
            rm -rf "${dir}.bak"
            mv "$dir" "${dir}.bak"
          fi
        done
      args:
        executable: /bin/bash
      register: backup_result
      changed_when: backup_result.stdout != ""

    - name: Clone LazyVim repository
      git:
        repo: https://github.com/LazyVim/starter
        dest: ~/.config/nvim
        version: main
        force: yes

    - name: Remove .git directory from LazyVim config
      file:
        path: ~/.config/nvim/.git
        state: absent

    - name: Install Nerd Fonts
      homebrew:
        name:
          - font-hack-nerd-font
          - font-fira-code-nerd-font
        state: present

    - name: Add Neovim alias to .zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'alias vim="nvim"'
        create: yes

    - name: Ensure LazyVim configuration directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.config/nvim/lua/config
        - ~/.config/nvim/lua/plugins

    - name: Add LazyVim configuration
      copy:
        dest: ~/.config/nvim/lua/config/options.lua
        content: |
          -- Add your own customizations here
          vim.opt.relativenumber = true
          vim.opt.wrap = false
          -- Add more options as needed

    - name: Add custom LazyVim plugins
      copy:
        dest: ~/.config/nvim/lua/plugins/user.lua
        content: |
          return {
            -- Add your custom plugins here
            { "tpope/vim-surround" },
            { "github/copilot.vim" },
            -- Add more plugins as needed
          }

    - name: Configure LazyVim colorschemes
      copy:
        dest: ~/.config/nvim/lua/plugins/colorscheme.lua
        content: |
          return {
            -- add gruvbox
            { "ellisonleao/gruvbox.nvim" },
            { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
            { "romgrk/github-light.vim" },
            -- Configure LazyVim to load catppuccin-frappe
            {
              "LazyVim/LazyVim",
              opts = {
                colorscheme = "catppuccin-frappe",
              },
            },
          }

  rescue:
    - name: Restore Neovim backups on failure
      ansible.builtin.shell: |
        for dir in ~/.config/nvim ~/.local/state/nvim ~/.cache/nvim; do
          if [ -d "${dir}.bak" ]; then
            rm -rf "$dir"
            mv "${dir}.bak" "$dir"
          fi
        done
      args:
        executable: /bin/bash
      when: backup_result is defined and backup_result.changed

    - name: Failure message
      debug:
        msg: "LazyVim setup failed. Original configurations have been restored."

  always:
    - name: Ensure Neovim directories have correct permissions
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"
      loop:
        - ~/.config/nvim
        - ~/.local/state/nvim
        - ~/.cache/nvim