- name: Set up LazyVim
  block:
    - name: Ensure Neovim is installed
      homebrew:
        name: neovim
        state: present

    - name: Backup Neovim directories
      ansible.builtin.shell: |
        for dir in ~/.config/nvim ~/.local/state/nvim ~/.cache/nvim; do
          if [ -d "$dir" ] && [ ! -d "${dir}.bak" ]; then
            mv "$dir" "${dir}.bak"
          elif [ -d "$dir" ] && [ -d "${dir}.bak" ]; then
            rm -rf "${dir}.bak"
            mv "$dir" "${dir}.bak"
          fi
        done
      args:
        executable: /bin/bash
      register: backup_result
      changed_when: backup_result.stdout != ""

    - name: Clone LazyVim repository
      ansible.builtin.git:
        repo: https://github.com/LazyVim/starter
        dest: ~/.config/nvim
        version: main
        force: true

    - name: Remove .git directory from LazyVim config
      ansible.builtin.file:
        path: ~/.config/nvim/.git
        state: absent

    - name: Install Nerd Fonts
      homebrew:
        name:
          - font-hack-nerd-font
          - font-fira-code-nerd-font
        state: present

    - name: Add Neovim alias to .zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'alias vim="nvim"'
        mode: '0644'
        create: true

    - name: Ensure LazyVim configuration directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.config/nvim/lua/config
        - ~/.config/nvim/lua/plugins

    - name: Add LazyVim configuration
      ansible.builtin.template:
        src: nvim_options.lua.j2
        dest: ~/.config/nvim/lua/config/options.lua
        mode: '0644'

    - name: Add custom LazyVim plugins
      ansible.builtin.template:
        src: nvim_plugins.lua.j2
        dest: ~/.config/nvim/lua/plugins/user.lua
        mode: '0644'

    - name: Configure LazyVim colorschemes
      ansible.builtin.template:
        src: nvim_colorscheme.lua.j2
        dest: ~/.config/nvim/lua/plugins/colorscheme.lua
        mode: '0644'

  rescue:
    - name: Restore Neovim backups on failure
      ansible.builtin.shell: |
        for dir in ~/.config/nvim ~/.local/state/nvim ~/.cache/nvim; do
          if [ -d "${dir}.bak" ]; then
            rm -rf "$dir"
            mv "${dir}.bak" "$dir"
          fi
        done
      args:
        executable: /bin/bash
      changed_when: false
      when: backup_result is defined and backup_result.changed

    - name: Failure message
      ansible.builtin.debug:
        msg: "LazyVim setup failed. Original configurations have been restored."

  always:
    - name: Ensure Neovim directories have correct permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"
      loop:
        - ~/.config/nvim
        - ~/.local/state/nvim
        - ~/.cache/nvim
