---
- name: Get list of installed VS Code extensions
  ansible.builtin.command: code --list-extensions
  register: installed_extensions
  changed_when: false

- name: Install VS Code extensions
  ansible.builtin.command: code --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"
  changed_when: false
  when: item not in installed_extensions.stdout_lines

- name: Ensure Catppuccin theme is installed
  ansible.builtin.command: code --install-extension Catppuccin.catppuccin-vsc
  changed_when: false
  when: '"Catppuccin.catppuccin-vsc" not in installed_extensions.stdout_lines'

- name: Configure VS Code settings
  ansible.builtin.template:
    src: vscode_settings.json.j2
    dest: ~/Library/Application Support/Code/User/settings.json
    mode: '0644'

- name: Configure VS Code keybindings
  ansible.builtin.template:
    src: vscode_keybindings.json.j2
    dest: ~/Library/Application Support/Code/User/keybindings.json
    mode: '0644'
